Audit history indexer flink job
project-sunbird/knowledge-platform-jobs pull request #111
Opened 2021-03-26 10:52 UTC by kumarks1122

2021-03-29 07:45 UTC, maheshkumargangula requested changes

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/resources/audit-history-indexer.conf
> +  }
this configuration is not required.

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +      logger.debug("Audit learning event received")
change to info log and mention for which identifier the audit is creating for.

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +        logger.debug("Saving the record into ES")
remove this
```suggestion

```

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +        logger.info("Audit record created for " + identifier)
move this to last statement.

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +      }
What are the possible scenarios to get the Exception here. If it is a ES connection issue, the job should fail. So, throw the exception to next level.

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +  }
We should consider the timezone also for creating the name of the index. Did you use the code from Samza for this?

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +    }
Why the if condition. Always replace it.

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/task/AuditHistoryIndexerConfig.scala
> +  val collectionCacheStore: Int = config.getInt("redis.database.collectionCache.id")
Do we need this?

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/test/resources/test.conf
> +  }
```suggestion

```

2021-03-29 07:45 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +  private def setSummaryData(transactionDataMap: Event): String = {
Is this summaryData required?

2021-03-29 12:00 UTC, maheshkumargangula requested changes

2021-03-29 12:00 UTC, maheshkumargangula commented on audit-history-indexer/project/build.properties
> +sbt.version=1.4.3
what is this file?

2021-03-29 12:01 UTC, kumarks1122 commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +  private def setSummaryData(transactionDataMap: Event): String = {
Yes @maheshkumargangula .

2021-03-29 13:40 UTC, maheshkumargangula approved these changes

2021-03-29 13:40 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +          summaryData ++= Map("tags"-> tags)
remove this.

2021-03-29 18:48 UTC, kumarks1122 commented on audit-history-indexer/project/build.properties
> +sbt.version=1.4.3
@maheshkumargangula : SBT build property file was added during new job creation. It is removed now.

2021-03-30 04:44 UTC, maheshkumargangula requested changes

2021-03-30 04:44 UTC, maheshkumargangula commented on audit-history-indexer/src/main/scala/org/sunbird/job/service/AuditHistoryIndexerService.scala
> +  private def setSummaryData(transactionDataMap: Event): String = {
remove summary computation.

2021-04-06 01:30 UTC, maheshkumargangula approved these changes

2021-04-06 17:35 UTC, merged