Flink job changes for adding content metrics for sourcing identifiers
project-sunbird/knowledge-platform-jobs pull request #233
Opened 2021-07-19 04:23 UTC by ishawakankar

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-21 10:35 UTC, maheshkumargangula requested changes

2021-07-21 10:35 UTC, maheshkumargangula commented on metrics-data-transformer/src/main/resources/metrics-data-transformer.conf
> +    learner.basePath = "http://localhost:9000/learning-service"
Please use content-service only for system update API. We don't need learning-service.

2021-07-21 10:35 UTC, maheshkumargangula commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/service/MetricsDataTransformerService.scala
> +    val response = getSourcingId(url)(config, httpUtil)
```suggestion
    val response = getContent(url)(config, httpUtil)
```

2021-07-21 10:35 UTC, maheshkumargangula commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/service/MetricsDataTransformerService.scala
> +  def getSourcingId(url: String)(config: MetricsDataTransformerConfig, httpUtil: HttpUtil) : Map[String,AnyRef] = {
```suggestion
  def getContent(url: String)(config: MetricsDataTransformerConfig, httpUtil: HttpUtil) : Map[String,AnyRef] = {
```

2021-07-21 10:35 UTC, maheshkumargangula commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/service/MetricsDataTransformerService.scala
> +        throw new Exception(s"Error writing metrics for sourcing id: $sourcingId")
Please throw the `ex` which is available already. Don't suppress it and create new.

2021-07-21 10:35 UTC, maheshkumargangula commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/task/MetricsDataTransformerConfig.scala
> +  val metrics: JList[String] = config.getStringList("data.metrics")
convert it to Scala List using `.asScala`.

2021-07-29 07:26 UTC, AmiableAnil commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/functions/MetricsDataTransformer.scala
> +class MetricsDataTransformer(config: MetricsDataTransformerConfig, httpUtil: HttpUtil)
rename the MetricsDataTransformer to MetricsDataTransformerFunction, as we are following the same other Function in the same repo.

2021-07-29 07:34 UTC, AmiableAnil commented on metrics-data-transformer/src/main/scala/org/sunbird/job/metricstransformer/functions/MetricsDataTransformer.scala
> +package org.sunbird.job.metricstransformer.functions
rename the package name from functions to function

2021-07-30 09:25 UTC, manjudr requested changes
Please add a grafana dashboard for this job, add more assertions and format the code.

2021-09-01 09:54 UTC, AmiableAnil commented
This PR is invalid, confirmed with @ishawakankar . Hence closing this PR.

2021-09-01 09:54 UTC, closed without merging