Issue #SB-25131: ECML publish code
project-sunbird/knowledge-platform-jobs pull request #252
Opened 2021-08-09 09:50 UTC by Jayaprakash8887

Issue #SB-25131: ECML publish code

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Unit Test case to be written

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2021-08-10 09:55 UTC, maheshkumargangula requested changes

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/resources/content-publish.conf
> +  bundleLocation = "/tmp"
```suggestion
  bundleLocation = "/tmp/contentBundle"
```

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +  def getS3URL(obj: ObjectData, cloudStorageUtil: CloudStorageUtil, config: ContentPublishConfig): String = {
```suggestion
  def getCloudStoreURL(obj: ObjectData, cloudStorageUtil: CloudStorageUtil, config: ContentPublishConfig): String = {
```

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +  private def getExtractionPath(obj: ObjectData, config: ContentPublishConfig, prefix: String): String = {
```suggestion
  private def getExtractionPath(obj: ObjectData, config: ContentPublishConfig, suffix: String): String = {
```

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +      case "application/vnd.ekstep.h5p-archive" => config.contentFolder + File.separator + "h5p" + File.separator + obj.identifier + "-" + prefix
```suggestion
      case "application/vnd.ekstep.ecml-archive" => config.contentFolder + File.separator + "ecml" + File.separator + obj.identifier + "-" + suffix
      case "application/vnd.ekstep.html-archive" => config.contentFolder + File.separator + "html" + File.separator + obj.identifier + "-" + suffix
      case "application/vnd.ekstep.h5p-archive" => config.contentFolder + File.separator + "h5p" + File.separator + obj.identifier + "-" + suffix
```

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +        case _: Exception => println("Remove try catch")
Why are we suppressing the exception here. Please remove the try catch statements.

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +      val downloadResultMap = Await.result(downloadAssetFiles(contentId, medias, basePath, config), Duration.apply("60 seconds"))
Please use configuration for download duration... Don't hard code it for 60 sec.

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/processor/IProcessor.scala
> +    val whiteListedMimeTypes: List[String] = List("application/vnd.ekstep.ecml-archive","application/vnd.ekstep.html-archive","application/vnd.android.package-archive","application/vnd.ekstep.content
Are you using this anywhere? This should come from a configuration or define it at config file. Otherwise, it is very difficult to identify this in future.

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +      case e: IOException => logger.error("Error! Something Went Wrong While Creating the ZIP File: " + e.getMessage, e)
We shouldn't suppress the Exception or Failure. Please throw the exception...

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +      case _: ParserConfigurationException | _: SAXException | _: IOException => false
Please log the error message here. That will explain what is wrong exactly with this XML content.

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +      case _: IOException => false
Please log the error message here. That will explain what is wrong exactly with this JSON content.

2021-08-10 09:55 UTC, maheshkumargangula commented on publish-pipeline/content-publish/src/main/scala/org/sunbird/job/content/publish/helpers/ExtractableMimeTypeHelper.scala
> +    obj.metadata ++ Map("artifactUrl" -> result(1), "cloudStorageKey" -> result(0), "s3Key" -> result(0))
```suggestion
    obj.metadata ++ Map("artifactUrl" -> result(1), "cloudStorageKey" -> result(0))
```
Stop stamping "s3Key". Let us deprecate and delete this property...

2021-08-10 10:26 UTC, AmiableAnil commented on publish-pipeline/content-publish/src/main/resources/content-publish.conf
> +  bundleLocation = "/tmp"
resolved

2021-08-12 10:15 UTC, maheshkumargangula approved these changes

2021-08-12 10:15 UTC, merged