Activity Aggregate refactoring
project-sunbird/knowledge-platform-jobs pull request #44
Opened 2020-11-09 09:59 UTC by maheshkumargangula

2020-11-09 17:24 UTC, SanthoshVasabhaktula requested changes

2020-11-09 17:24 UTC, SanthoshVasabhaktula commented on activity-aggregate-updater/src/main/scala/org/sunbird/job/functions/ActivityAggregatesFunction.scala
> +    } else false
unique check should be done for all contents, not the first one. And there may be possibility that some of the contents within an event can be duplicate. The method needs to change to discardDuplicates(event) which would return a List of userId, courseId, batchId, contentId, status. This should also filter out the events with status=1

2020-11-12 09:30 UTC, SanthoshVasabhaktula requested changes

2020-11-12 09:30 UTC, SanthoshVasabhaktula commented on activity-aggregate-updater/src/main/scala/org/sunbird/job/functions/ActivityAggregatesFunction.scala
>      }
Convert this into a case class of (batchId, courseId, contentId, userId, status)

2020-11-12 09:30 UTC, SanthoshVasabhaktula commented on activity-aggregate-updater/src/main/scala/org/sunbird/job/task/ActivityAggregateUpdaterStreamTask.scala
>          .timeWindow(Time.seconds(config.thresholdBatchReadInterval))
Why don't we do a key by userId modulus 2000 (shards) and do a countWindow(100)? @maheshkumargangula @anandp504

2020-11-12 09:57 UTC, anandp504 commented on activity-aggregate-updater/src/main/scala/org/sunbird/job/task/ActivityAggregateUpdaterStreamTask.scala
>          .timeWindow(Time.seconds(config.thresholdBatchReadInterval))
@SanthoshVasabhaktula I am working on making the change to use a mod of userId as the partition key.

2020-11-18 04:07 UTC, merged