Issue #SB-31006 fix: Content linking to collection is failing.
project-sunbird/knowledge-platform-jobs pull request #608
Opened 2022-09-28 13:14 UTC by Jayaprakash8887

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran Unit Test

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-09-28 16:43 UTC, vinukumar-vs requested changes

2022-09-28 16:43 UTC, vinukumar-vs commented on content-auto-creator/src/main/scala/org/sunbird/job/contentautocreator/helpers/ContentAutoCreator.scala
> +			delay(config.publishDelay)
Why is this delay is added now. How the code was working without this delay till now.
What is the root cause for the issue?

2022-09-29 04:42 UTC, Jayaprakash8887 commented on content-auto-creator/src/main/scala/org/sunbird/job/contentautocreator/helpers/ContentAutoCreator.scala
> +			delay(config.publishDelay)
Root cause: there is some time taken for content to get published but I am reading status of content almost immediately after sending content for publish. So, status is not live because of which collection linking was getting skipped. Karteek said, i should allow draft contents to be linked in VDN. So updated to check status not equal to "Failed"

2022-09-29 06:13 UTC, vinukumar-vs approved these changes

2022-09-29 06:13 UTC, merged